language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  global:
  #encrypted HOMEBREW_GITHUB_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "Wmt2VTt52QrAeXSU2oBDeS9d5/79BOFV4JikeTYi+Wsk+Kh9aGkqxnonTwrHQa2XAxqLIOIjIWoBWDr7GouhsjsOt9gWSk96w12zxvSWb3IZLlPqNGlnV1koENjtKc91hnwDUJch8zi+KS1iq4a5X0NWa6kjlXDDIuncQJ6XVExdkawgGSyw0V/eGAomz8yMGs+a87W1o1iaXGe9hW6mP8xeNz/IGlm27nMLPnPiePIkyypLjCyVXrRcCQRrM1NGo2Ko/fA/4v8IgItwCtUJZHWVPnYfNBCpfR9rfo42UBFbZ/aiqLrjWvKgkszRicaYwtosD3+cCB4ajXm8z0cDOWa4xqEuYDep92B9eA+RKV2xdVWrQqIYyWASPmnhm1ysJAxWXdBFoT0zXpOeBXFwg3sEO7S+/4ShICKdbXaZEgCtl5MQs5F3EXk8vMPFDipu1EbZLVZJCDzBUK/ov7DcGPVw3WxKTuaeROY+flhqXHLyeiCTH1vRzty5ltpIZqLKT0RfDcvUgaylf3DcP+4w63G2AHrqQbQxVhIVcQRGslQefGJftTOIG6qREepg+YjRDjQ9KMGUYVk1U98ER4qMJwlI7sP356VenisqkfTUQMimGcf4EzRT9Zh27urtQyIxRMSyI34gFo8QgXEyrxkjZH7vMHgRKvRhhyuKd4pwM0c="
  - HOMEBREW_GITHUB_USERNAME=igagis

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    echo "deb https://dl.bintray.com/igagis/deb /" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null;
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61;
    sudo apt-get update -qq;
    sudo apt-get install -qq debhelper prorab doxygen;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew tap igagis/tap;
    brew update > /dev/null;
    brew install prorab;
  fi


script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    make deb;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    make;
    make test;
  fi

deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
  file: travis_bintray.json
  user: igagis
  key:
    secure: "E3q8rPR8oqmLX4ZNqh0V0hTzPxS6lB5sqtCa3nGNZH7nnRpHTjU4zkQkpgXCRC0ebuizdjiXlGvLRoFFpVWu0walPKSsN6GRdwoxQDBrFYlsX63xkF4CTTzPZnbWPWJhZcFAU4qUGwXuKhKjSUWSTlXSZSV924DQPUcqZ2yM6kyzdg0wKPRw5mYfVlt1ccn22oCgVOnKM9d8RA6P8HOGYbQK5M6yJsgzKO+1lFrADPI7uWd7plJqq/S9Ta6W7yFFeJaU1m7D1Uvjvl96C8PhTH4UZ+cpchvdB2tGL9rJ14j9gBUpxQ2HwlADNC/o+UuRGEbw28boKterpsO2tjstI6hAJpJu2Qpim8Wz1SHr0hSCoiomEigtktXA61UcivKFbbdCGv4vMCXQV9wQ8RJVHMvh0CoX8ibrc60F6piVIp+ZQwdmtutNb9osx3DdUd/Hp1ITcf5Q2uKzGypas+u1ILDktXf7kGIRjMtMZr+vwGLR6gjMAx+I4LhlYVTTY7e3BmR5/2IpUIHMSlTntETMUv6eC4xIHmHYjfv8Ypd/j3qmrB11V81pGc+NBUC7wiNyMfEMzIZ3vbhhDhIGn7bZ4NyH4gb/bDVXzN4riFsou2/CP7p96Hm5bO60iq+hsqYxdzwfsf0nR/dvrfpv9dNhjbnldmAKJChXGQ2sKn3xswE="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: prorab-deploy-homebrew.sh igagis/tap
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
