branches:
  except:
  - release

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: required
      language: cpp
      dist: trusty
      env: BUILD_NAME=debian
    - os: osx
      osx_image: xcode7.3
      sudo: required
      compiler: clang
      language: cpp
      env: BUILD_NAME=macosx
    - language: android
      env: BUILD_NAME=android

      
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
#    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository


env:
  global:
  #encrypted PRORAB_GIT_ACCESS_TOKEN for publishing to git-based repos
  secure: "a9c0rHQ4xMd3SfxFaOcrw5ot6su3PI+x0eZUCuvYREcoRFIKCcYw+CETZuPAsZ2uT49tONTy5rafOBcCuMl/GQ5ZE5leeou6xiofj4kKv1tiJL1j8Ek1gELJ4dnXHMbpmyYIhuW7LZ1C+BellYIzLizJv+rcdEGQBkFhZPQDPV3cpxhoOctVp4fJR+bD/WOPsmU4gVi7cbc2iOBvGEe0dFch2ZK4M5X0oO75W2vXybFeAzhZdR6lA3mcyEtrVSKEpUGrvWKaMbLaGyZal3kH71Jtl8IcpzhReGb7AOPjWSomRWJHkLS/89zjLgMBe/oXCeZEjEqwOSOwxDo5gmgSxRUyUSmASUA9hi9x2DJBpt8iTdjO+cSG6FWf13KrlyUfJyCjIpVkD8sDvV15kXHr0EeK3p7o5Qj7OP06nv56CzI/ELsvBJKTLAYwiA7saKJvQ3uwmwJafvsXVgPgpdFHYDLUWw5B5DNFXcqt0mo32Cy/I/T9Sr0XWjdpoe7fw/Z4uG4SsUM17T67UnyDZ7DnYUDqcs4g3j3cbc4fR9CrSDU9f0+3AD49XrWYNGSfiL6I1EH3LsdSrTklNs27vx1h4ns8luOOCh5b16388MXp/uXikOIyhEkeYNAwVnMaapK+9p0+MOCqiZQV9ZqF+aXH+jFYVNXNVL4hf77FMGR6+So="
  - PRORAB_GIT_USERNAME=igagis
  - USE_ANDROID_NDK_VERSION=15c

before_install:
- if [ "$BUILD_NAME" == "debian" ]; then
    echo "deb https://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq debhelper prorab doxygen fakeroot;
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    echo "deb https://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq prorab;
  fi
- if [ "$BUILD_NAME" == "macosx" ]; then
    rvm install ruby-2.2.2 &&
    rvm use ruby-2.2.2 &&
    
    rvm 2.2.1 do gem uninstall bundler -v '>1.12.5' --force &&
    rvm 2.2.1 do gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet &&
    
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$PRORAB_GIT_USERNAME:$PRORAB_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&

    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install prorab;
  fi


before_script:
  # download and install android NDK
  - if [ "$BUILD_NAME" == "android" ]; then
      export TERM=dumb &&
      curl -L https://dl.google.com/android/repository/android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip -O &&
      unzip ./android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip > /dev/null &&
      rm android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip &&
      export ANDROID_NDK_HOME=`pwd`/android-ndk-r$USE_ANDROID_NDK_VERSION &&
      export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME" &&
      export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64" &&
      export PATH=$PATH:${ANDROID_NDK_HOME} &&
      env;
    fi


script:
- if [ "$BUILD_NAME" == "debian" ]; then
    prorab-deb-prepare.sh &&
    dpkg-buildpackage -us -uc;
  fi
- if [ "$BUILD_NAME" == "macosx" ]; then
    make &&
    make test &&

    xcodebuild -project ios/tests.xcodeproj/ -alltargets CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO;
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    (cd android && ./gradlew build) &&
    prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` android/*.pom.in &&
    prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` android/*.aar.in --filename-only;
  fi

before_deploy:
  - prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` travis_bintray_*.json.in

deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = debian
  file: travis_bintray_deb.json
  user: igagis
  key:
    secure: "E3q8rPR8oqmLX4ZNqh0V0hTzPxS6lB5sqtCa3nGNZH7nnRpHTjU4zkQkpgXCRC0ebuizdjiXlGvLRoFFpVWu0walPKSsN6GRdwoxQDBrFYlsX63xkF4CTTzPZnbWPWJhZcFAU4qUGwXuKhKjSUWSTlXSZSV924DQPUcqZ2yM6kyzdg0wKPRw5mYfVlt1ccn22oCgVOnKM9d8RA6P8HOGYbQK5M6yJsgzKO+1lFrADPI7uWd7plJqq/S9Ta6W7yFFeJaU1m7D1Uvjvl96C8PhTH4UZ+cpchvdB2tGL9rJ14j9gBUpxQ2HwlADNC/o+UuRGEbw28boKterpsO2tjstI6hAJpJu2Qpim8Wz1SHr0hSCoiomEigtktXA61UcivKFbbdCGv4vMCXQV9wQ8RJVHMvh0CoX8ibrc60F6piVIp+ZQwdmtutNb9osx3DdUd/Hp1ITcf5Q2uKzGypas+u1ILDktXf7kGIRjMtMZr+vwGLR6gjMAx+I4LhlYVTTY7e3BmR5/2IpUIHMSlTntETMUv6eC4xIHmHYjfv8Ypd/j3qmrB11V81pGc+NBUC7wiNyMfEMzIZ3vbhhDhIGn7bZ4NyH4gb/bDVXzN4riFsou2/CP7p96Hm5bO60iq+hsqYxdzwfsf0nR/dvrfpv9dNhjbnldmAKJChXGQ2sKn3xswE="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = debian
  file: travis_bintray_ubu.json
  user: igagis
  key:
    secure: "E3q8rPR8oqmLX4ZNqh0V0hTzPxS6lB5sqtCa3nGNZH7nnRpHTjU4zkQkpgXCRC0ebuizdjiXlGvLRoFFpVWu0walPKSsN6GRdwoxQDBrFYlsX63xkF4CTTzPZnbWPWJhZcFAU4qUGwXuKhKjSUWSTlXSZSV924DQPUcqZ2yM6kyzdg0wKPRw5mYfVlt1ccn22oCgVOnKM9d8RA6P8HOGYbQK5M6yJsgzKO+1lFrADPI7uWd7plJqq/S9Ta6W7yFFeJaU1m7D1Uvjvl96C8PhTH4UZ+cpchvdB2tGL9rJ14j9gBUpxQ2HwlADNC/o+UuRGEbw28boKterpsO2tjstI6hAJpJu2Qpim8Wz1SHr0hSCoiomEigtktXA61UcivKFbbdCGv4vMCXQV9wQ8RJVHMvh0CoX8ibrc60F6piVIp+ZQwdmtutNb9osx3DdUd/Hp1ITcf5Q2uKzGypas+u1ILDktXf7kGIRjMtMZr+vwGLR6gjMAx+I4LhlYVTTY7e3BmR5/2IpUIHMSlTntETMUv6eC4xIHmHYjfv8Ypd/j3qmrB11V81pGc+NBUC7wiNyMfEMzIZ3vbhhDhIGn7bZ4NyH4gb/bDVXzN4riFsou2/CP7p96Hm5bO60iq+hsqYxdzwfsf0nR/dvrfpv9dNhjbnldmAKJChXGQ2sKn3xswE="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = debian
  file: travis_bintray_rasp.json
  user: igagis
  key:
    secure: "E3q8rPR8oqmLX4ZNqh0V0hTzPxS6lB5sqtCa3nGNZH7nnRpHTjU4zkQkpgXCRC0ebuizdjiXlGvLRoFFpVWu0walPKSsN6GRdwoxQDBrFYlsX63xkF4CTTzPZnbWPWJhZcFAU4qUGwXuKhKjSUWSTlXSZSV924DQPUcqZ2yM6kyzdg0wKPRw5mYfVlt1ccn22oCgVOnKM9d8RA6P8HOGYbQK5M6yJsgzKO+1lFrADPI7uWd7plJqq/S9Ta6W7yFFeJaU1m7D1Uvjvl96C8PhTH4UZ+cpchvdB2tGL9rJ14j9gBUpxQ2HwlADNC/o+UuRGEbw28boKterpsO2tjstI6hAJpJu2Qpim8Wz1SHr0hSCoiomEigtktXA61UcivKFbbdCGv4vMCXQV9wQ8RJVHMvh0CoX8ibrc60F6piVIp+ZQwdmtutNb9osx3DdUd/Hp1ITcf5Q2uKzGypas+u1ILDktXf7kGIRjMtMZr+vwGLR6gjMAx+I4LhlYVTTY7e3BmR5/2IpUIHMSlTntETMUv6eC4xIHmHYjfv8Ypd/j3qmrB11V81pGc+NBUC7wiNyMfEMzIZ3vbhhDhIGn7bZ4NyH4gb/bDVXzN4riFsou2/CP7p96Hm5bO60iq+hsqYxdzwfsf0nR/dvrfpv9dNhjbnldmAKJChXGQ2sKn3xswE="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = android
  file: travis_bintray_android.json
  user: igagis
  key:
    secure: "E3q8rPR8oqmLX4ZNqh0V0hTzPxS6lB5sqtCa3nGNZH7nnRpHTjU4zkQkpgXCRC0ebuizdjiXlGvLRoFFpVWu0walPKSsN6GRdwoxQDBrFYlsX63xkF4CTTzPZnbWPWJhZcFAU4qUGwXuKhKjSUWSTlXSZSV924DQPUcqZ2yM6kyzdg0wKPRw5mYfVlt1ccn22oCgVOnKM9d8RA6P8HOGYbQK5M6yJsgzKO+1lFrADPI7uWd7plJqq/S9Ta6W7yFFeJaU1m7D1Uvjvl96C8PhTH4UZ+cpchvdB2tGL9rJ14j9gBUpxQ2HwlADNC/o+UuRGEbw28boKterpsO2tjstI6hAJpJu2Qpim8Wz1SHr0hSCoiomEigtktXA61UcivKFbbdCGv4vMCXQV9wQ8RJVHMvh0CoX8ibrc60F6piVIp+ZQwdmtutNb9osx3DdUd/Hp1ITcf5Q2uKzGypas+u1ILDktXf7kGIRjMtMZr+vwGLR6gjMAx+I4LhlYVTTY7e3BmR5/2IpUIHMSlTntETMUv6eC4xIHmHYjfv8Ypd/j3qmrB11V81pGc+NBUC7wiNyMfEMzIZ3vbhhDhIGn7bZ4NyH4gb/bDVXzN4riFsou2/CP7p96Hm5bO60iq+hsqYxdzwfsf0nR/dvrfpv9dNhjbnldmAKJChXGQ2sKn3xswE="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: prorab-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $BUILD_NAME = macosx
- provider: script
  skip_cleanup: true
  script: rvm 2.2.1 do prorab-deploy-cocoapods.sh -r igagis
  on:
    tags: true
    condition: $BUILD_NAME = macosx
